# Generated by Django 4.1.7 on 2023-03-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hightest_level',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
