# Generated by Django 4.1.7 on 2023-03-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='inviter',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='members',
        ),
    ]
