# Generated by Django 4.1.7 on 2023-03-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_membership_inviter_remove_userstatus_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStatus',
            new_name='Status',
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'status')},
        ),
    ]
