# Generated by Django 4.1.7 on 2023-03-05 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_userstatus_status_alter_membership_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['user', '-date']},
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='name',
        ),
        migrations.AddField(
            model_name='status',
            name='members',
            field=models.ManyToManyField(through='home.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
