# Generated by Django 4.1.7 on 2023-05-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['legal_entity', 'name']},
        ),
        migrations.AlterModelOptions(
            name='installation',
            options={'ordering': ['client']},
        ),
        migrations.RenameField(
            model_name='legalentity',
            old_name='entity',
            new_name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='is_still_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('legal_entity', 'name')},
        ),
    ]
