# Generated by Django 4.1.7 on 2023-05-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_options_alter_installation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='is_still_in_service',
            field=models.BooleanField(default=True),
        ),
    ]
